version: '3.1'

services:
  db:
    container_name: social_network_db
    image: postgres:latest
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: social_network_db
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d postgres
      - ./data/postgres:/var/lib/postgresql/data