version: '3.1'

services:
  db:
    container_name: social_network_db
    image: postgres:latest
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: social_network_db
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d postgres
      - ./data/postgres:/var/lib/postgresql/data

  service_online:
    container_name: social_network_app
    image: social_network_app:dev
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "81:8000"
    command: [ "uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8000" ]

    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: curl -sS http://127.0.0.1:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3